spring:
  application:
    name: paymentsvc
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: never
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    topic:
      result: payment-command-result
      source: payment-command
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    bootstrap-servers:
      - kafka:9092
    topics:
      - name: payment-command
        partitions: 1
        replicationFactor: 1
      - name: payment-command-result
        partitions: 1
        replicationFactor: 1
  server:
    port: ${PAYMENT_SERVICE_PORT}
